/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRequestPasswordResetRouteImport } from './routes/auth/request-password-reset'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AuthResetPasswordCallbackIdRouteImport } from './routes/auth/reset-password.$callbackId'
import { Route as AppPackNewRouteImport } from './routes/_app/pack.new'
import { Route as AppPackIdRouteImport } from './routes/_app/pack.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRequestPasswordResetRoute =
  AuthRequestPasswordResetRouteImport.update({
    id: '/request-password-reset',
    path: '/request-password-reset',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AuthResetPasswordCallbackIdRoute =
  AuthResetPasswordCallbackIdRouteImport.update({
    id: '/reset-password/$callbackId',
    path: '/reset-password/$callbackId',
    getParentRoute: () => AuthRoute,
  } as any)
const AppPackNewRoute = AppPackNewRouteImport.update({
  id: '/pack/new',
  path: '/pack/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPackIdRoute = AppPackIdRouteImport.update({
  id: '/pack/$id',
  path: '/pack/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/inventory': typeof AppInventoryRoute
  '/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/request-password-reset': typeof AuthRequestPasswordResetRoute
  '/pack/$id': typeof AppPackIdRoute
  '/pack/new': typeof AppPackNewRoute
  '/auth/reset-password/$callbackId': typeof AuthResetPasswordCallbackIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/inventory': typeof AppInventoryRoute
  '/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/request-password-reset': typeof AuthRequestPasswordResetRoute
  '/': typeof AppIndexRoute
  '/pack/$id': typeof AppPackIdRoute
  '/pack/new': typeof AppPackNewRoute
  '/auth/reset-password/$callbackId': typeof AuthResetPasswordCallbackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/request-password-reset': typeof AuthRequestPasswordResetRoute
  '/_app/': typeof AppIndexRoute
  '/_app/pack/$id': typeof AppPackIdRoute
  '/_app/pack/new': typeof AppPackNewRoute
  '/auth/reset-password/$callbackId': typeof AuthResetPasswordCallbackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/inventory'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/auth/request-password-reset'
    | '/pack/$id'
    | '/pack/new'
    | '/auth/reset-password/$callbackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/inventory'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/auth/request-password-reset'
    | '/'
    | '/pack/$id'
    | '/pack/new'
    | '/auth/reset-password/$callbackId'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/inventory'
    | '/_app/settings'
    | '/auth/login'
    | '/auth/register'
    | '/auth/request-password-reset'
    | '/_app/'
    | '/_app/pack/$id'
    | '/_app/pack/new'
    | '/auth/reset-password/$callbackId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/request-password-reset': {
      id: '/auth/request-password-reset'
      path: '/request-password-reset'
      fullPath: '/auth/request-password-reset'
      preLoaderRoute: typeof AuthRequestPasswordResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/reset-password/$callbackId': {
      id: '/auth/reset-password/$callbackId'
      path: '/reset-password/$callbackId'
      fullPath: '/auth/reset-password/$callbackId'
      preLoaderRoute: typeof AuthResetPasswordCallbackIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/pack/new': {
      id: '/_app/pack/new'
      path: '/pack/new'
      fullPath: '/pack/new'
      preLoaderRoute: typeof AppPackNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pack/$id': {
      id: '/_app/pack/$id'
      path: '/pack/$id'
      fullPath: '/pack/$id'
      preLoaderRoute: typeof AppPackIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInventoryRoute: typeof AppInventoryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPackIdRoute: typeof AppPackIdRoute
  AppPackNewRoute: typeof AppPackNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInventoryRoute: AppInventoryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppPackIdRoute: AppPackIdRoute,
  AppPackNewRoute: AppPackNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthRequestPasswordResetRoute: typeof AuthRequestPasswordResetRoute
  AuthResetPasswordCallbackIdRoute: typeof AuthResetPasswordCallbackIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthRequestPasswordResetRoute: AuthRequestPasswordResetRoute,
  AuthResetPasswordCallbackIdRoute: AuthResetPasswordCallbackIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
